### ISSUE TITLE
TODO : MERCOLEDI

### ISSUE THREAD

**Issue by DanerSound** [DanerSound/ProgettoArchitetture-1819#26]
CERCARE DI COMPLETARE L'ELENCO DELLE COSE DA FARE ENTRO IL POMERIGGIO
- [x] PRENDERE ALGORITMO A E GENERALIZZARLO
- [x] FAR ITERARE ALGORITMOA LAVORANDO CON UNA STRINGA DA MEMORIA
- [x] FAR ITERARE ALGORITMO-A LEGGENDO DA UN FILE
- [x] cercare di combinare l'algoritmo A con #27 per generare ALGORITMO B , C
- [x] mettere algoritmo D collegato direttamente da master

**Comment by Wabri** [comment]
questo è diventato un todo mercoledì +6 giorni?

**Comment by DanerSound** [comment]
Non ho capito
