### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DanerSound** [DanerSound/ProgettoArchitetture-1819#55]
- [x] FARE REFACTORING DI MASTERVESIONE2 : ASSEGNARE NOMI PIÙ SIGNIFICATIVI E MIGLIORARE I COMMENTI
- [x] ASTRARRE DALLA PROCEDURA CORE IL SETTAGGIO DELLE VARIABILI DEDICATE AGLI ALGORTIMI
- [x] ASTRARRE DENTRO IL MAIN LA LETTURA DEI FILE E IL CARICAMENTO DEI BUFFER IN ENTRAMBE LE FASE
- [ ] fare primi disegni per la relazione
