### ISSUE TITLE
TODO x FINIRE IL PROGETTO

### ISSUE THREAD

**Issue by DanerSound** [DanerSound/ProgettoArchitetture-1819#60]
- [x] generalizzare i flag degli stati
- [x] far tornare l'algoritmo D dentro masterVersion2
- [x] scrivere la decifratura algoritmo E
- [ ] insierire cifratura e decifratura  dell algoritmo E in master Versione2 e far tornare
- [x] fare la procedura che scrive su file, sarà sua la resposabilita di chiamare il metodo che trasforma il carattare ascii in numero
- [ ] fare la relazione : completare le note
